- hosts: tor_nxos
  connection: network_cli
  gather_facts: false
  tasks: 
    - name: run show version
      nxos_facts:
    - debug:
        var: ansible_net_version
    - name: create vlan
      cisco.nxos.nxos_vlans:
        config:
        - vlan_id: 11
          name: soheil50w00
        - vlan_id: 12
          name: soheil1w000
    - name: Delete vlans.
      cisco.nxos.nxos_vlans:
        config:
        - vlan_id: 500
        - vlan_id: 1000
        state: deleted